### PR TITLE
Remove dedicated close button, added some comments, added tool tips for a couple of the buttons

### PR DESCRIPTION
**Pull request by superboo07**
I removed the dedicated close button because every browser already has one, making the button useless. I have also added some comments to the code. Then I added some tooltips to a couple of the buttons. (Now when you hover over a few of the buttons it will show a text box telling the user what the button does.

### CODE REVIEW

**Comment by superboo07** [comment]
The reason I am removing the close button, is because it is taking up valuable space, and because every single browser already has a close button. 

image

**Comment by hacknorris-notyetbanned** [comment]
Yeah but i work on borderless version... And there it'll need to be...

**Comment by hacknorris-notyetbanned** [comment]
Yeah but i work on borderless version... And there it'll need to be...

**Comment by superboo07** [comment]
Well, until that version is released. I recommend removing the close button. In fact, once that version is released, I'd recommend only having the dedicated close button in the borderless version. It has no use in the non borderless version.

**Comment by hacknorris-notyetbanned** [comment]
Do upyou know that's possible in html to hide elements? You just could hide that...

**Comment by hacknorris-notyetbanned** [comment]
Go there and look : https://stackoverflow.com/questions/2928688/how-to-hide-elements-without-having-them-take-space-on-the-page

**Comment by hacknorris-notyetbanned** [comment]
Done but you forgot about `visibility:hidden`

**Pull request merged**
